theme = "solarized-dark"
#icons = "material"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
warning_mem = 80.0
critical_mem = 95.0

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "temperature"
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "load"
interval = 1
format = "{1m}"

#[[block]]
#block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_up = true
graph_up = true
interval = 5

[[block]]
block = "nvidia_gpu"
label = "GTX 1050Ti"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
